In [95]:
import pennylane as qml

def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=0)
    return qml.expval(qml.PauliZ(0))

In [96]:
qfunc(0.1,0.2)

expval(PauliZ(wires=[0]))

In [97]:
dev = qml.device("default.qubit",wires = 2)

In [98]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=0)
    return qml.expval(qml.PauliZ(0))

In [99]:
qfunc(0.1,0.2)

tensor(0.97517033, requires_grad=True)

In [100]:
qfunc

In [101]:
print(qml.draw(qfunc)(0.1,0.2))

 0: ──RX(0.1)──RY(0.2)──┤ ⟨Z⟩ 



In [102]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=1)
    qml.CNOT(wires=[0,1])
    return qml.expval(qml.PauliZ(0)), qml.var(qml.PauliX(1))

In [103]:
qfunc(0.1,0.2)

tensor([0.99500417, 0.9605305 ], requires_grad=True)

In [104]:
print(qml.draw(qfunc)(0.1,0.2))

 0: ──RX(0.1)──╭C──┤ ⟨Z⟩    
 1: ──RY(0.2)──╰X──┤ Var[X] 



In [105]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=1)
    qml.CNOT(wires=[0,1])
    return qml.probs(wires=[0,1])

In [106]:
qfunc(0.1,0.2)

tensor([9.87560268e-01, 9.94181506e-03, 2.48960206e-05, 2.47302134e-03], requires_grad=True)

In [107]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=1)
    qml.CNOT(wires=[0,1])
    return qml.probs(wires=[0]),qml.probs(wires=[1])

In [108]:
qfunc(0.1,0.2)

tensor([[0.99750208, 0.00249792],
        [0.98758516, 0.01241484]], requires_grad=True)

In [109]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=1)
    qml.CNOT(wires=[0,1])
    return qml.state()

In [110]:
qfunc(0.1,0.2)

tensor([0.99376067+0.j        , 0.09970865+0.j        ,
        0.        -0.00498959j, 0.        -0.04972948j], requires_grad=True)

In [111]:
dev = qml.device("default.qubit",wires = 2,analytic = False, shots = 100)

In [112]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=0)
    return qml.expval(qml.PauliZ(0))

In [113]:
qfunc(0.1,0.2)

tensor(1., requires_grad=True)

In [114]:
qfunc(0.1,0.2)

tensor(0.94, requires_grad=True)

In [115]:
qfunc(0.1,0.2)

tensor(0.96, requires_grad=True)

In [116]:
qfunc(0.1,0.2)

tensor(0.98, requires_grad=True)

In [117]:
qfunc(0.1,0.2)

tensor(0.98, requires_grad=True)

In [118]:
qfunc(0.1,0.2)

tensor(1., requires_grad=True)

In [119]:
dev = qml.device("default.qubit",wires = 2,analytic = False, shots = 1000)

In [120]:
@qml.qnode(dev)
def qfunc(x, y):
    qml.RX(x, wires=0)
    qml.RY(y,wires=0)
    return qml.expval(qml.PauliZ(0))

In [121]:
qfunc(0.1,0.2)

tensor(0.978, requires_grad=True)

In [122]:
qfunc(0.1,0.2)

tensor(0.986, requires_grad=True)

In [123]:
qfunc(0.1,0.2)

tensor(0.974, requires_grad=True)

In [124]:
qfunc(0.1,0.2)

tensor(0.976, requires_grad=True)

In [125]:
qfunc(0.1,0.2)

tensor(0.972, requires_grad=True)

# VQC for calculating gradients

In [126]:
dev = qml.device("default.qubit",wires = 2)

In [127]:
@qml.qnode(dev)
def circuit(params):
    qml.RX(params[0], wires=0)
    qml.RY(params[1],wires=1)
    qml.CNOT(wires = [0,1])
    qml.RZ(params[2], wires = 0)
    qml.RZ(params[2], wires = 1)
    qml.CNOT(wires = [1,0])
    qml.Hadamard(wires = 0)
    return qml.expval(qml.PauliZ(0) @ qml.PauliX(1)) # tensor product

In [128]:
from pennylane import numpy as np #enables automatic diff

In [129]:
params = np.array([0.1,0.2,0.3], requires_grad = True)

In [130]:
circuit(params)

tensor(0.18979606, requires_grad=True)

In [131]:
grad_fn = qml.grad(circuit)

In [132]:
grad_fn

In [133]:
grad_fn(params)

(array([-3.81639165e-17,  9.36293364e-01, -5.87108017e-02]),)

In [134]:
#parameter shift rule - checking the gradients manually

In [135]:
shift = np.array([0, 0, np.pi/2])

In [136]:
(circuit(params+shift)- circuit(params - shift))/2

tensor(-0.0587108, requires_grad=True)

In [137]:
def cost(params, y):
    output_quantum = circuit(np.sin(params) + y)
    return np.cos(output_quantum) ** 3

In [138]:
cost(params, 0.5)

tensor(0.72989252, requires_grad=True)

In [139]:
grad_fn = qml.grad(circuit)

In [140]:
grad_fn = qml.grad(cost)

In [141]:
grad_fn(params,0.5)

(tensor([ 8.28507400e-17, -5.55825356e-01,  4.64428974e-01], requires_grad=True),
 array(-0.08098843))

# optimisation

In [142]:
dev = qml.device("default.qubit",wires = 1)

In [143]:
@qml.qnode(dev)
def qfunc(params):
    qml.RX(params[0], wires = 0)
    qml.RY(params[1], wires = 0)
    return qml.probs(wires = 0)

In [144]:
params = np.array([0.1,0.2], requires_grad = True)

In [145]:
qfunc(params)

tensor([0.98758516, 0.01241484], requires_grad=True)

In [147]:
# optimising the circuit to measure the circuit in the excited state

In [148]:
def cost(params):
    output = qfunc(params)
    return output[0] - output[1]

In [149]:
cost(params)

tensor(0.97517033, requires_grad=True)

In [150]:
opt = qml.GradientDescentOptimizer(0.1)

In [151]:
for i in range(50):
    params, cost_val = opt.step_and_cost(cost, params)
    print(F"step{i}, cost {cost_val}")

step0, cost 0.9751703272018162
step1, cost 0.9700726698587928
step2, cost 0.9639570957069223
step3, cost 0.9566331225488502
step4, cost 0.9478802437539097
step5, cost 0.9374456604955514
step6, cost 0.9250430023927451
step7, cost 0.9103526578101176
step8, cost 0.8930245009217394
step9, cost 0.872683943543075
step10, cost 0.8489423007018884
step11, cost 0.8214123584732697
step12, cost 0.7897296674235479
step13, cost 0.7535793508704921
step14, cost 0.7127270543099405
step15, cost 0.6670511268211622
step16, cost 0.6165714702566927
step17, cost 0.5614692154133246
step18, cost 0.5020911734926485
step19, cost 0.43893452463795785
step20, cost 0.3726107064712659
step21, cost 0.30379245673770644
step22, cost 0.23315308378844063
step23, cost 0.1613104322977743
step24, cost 0.08878811794940683
step25, cost 0.016002955347644954
step26, cost -0.05671896805439741
step27, cost -0.12910246618516108
step28, cost -0.20087065270467575
step29, cost -0.2716937585053097
step30, cost -0.34115320064510507
step

In [154]:
params #updated parameters

tensor([0.09887443, 2.95914923], requires_grad=True)

In [155]:
qfunc(params)

tensor([0.01069986, 0.98930014], requires_grad=True)

In [156]:
# plugins and devcices

In [157]:
pip install amazon-braket-pennylane-plugin

In [183]:
device_braket = qml.device("braket.local.qubit",wires = 2, shots = 1000)

In [184]:
@qml.qnode(device_braket)
def circuit_qubit(params):
    qml.RX(params[0],wires = 0)
    qml.RY(params[0],wires = 0)
    qml.CNOT(wires = [0,1])
    qml.Hadamard(wires = 1)
    return qml.expval(qml.PauliY(1))

In [185]:
dev_photonic = qml.device("default.gaussian",wires = 2)

In [186]:
@qml.qnode(dev_photonic)
def circuit_photonic(x,y):
    qml.Squeezing(x,0,wires = 0)
    qml.Beamsplitter(y,0,wires=[0,1])
    return qml.expval(qml.NumberOperator(0))

In [187]:
circuit_photonic(0.2,0.6)

tensor(0.02761239, requires_grad=True)

In [188]:
def cost(params):
    out1 = np.exp(circuit_qubit(params))
    out2 = circuit_photonic(out1,out1 **3)
    return np.sum(out2 - out1)

In [189]:
params = np.array([0.2,0.1,0.3], requires_grad = True)

In [190]:
cost(params)

tensor(-0.71576451, requires_grad=True)

In [191]:
qml.grad(cost)(params)

(array([0.00864645, 0.        , 0.        ]),)